//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.239
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iKiwi.Properties {
	using System;
	
	
	/// <summary>
	///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
	/// </summary>
	// Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
	// tramite uno strumento quale ResGen o Visual Studio.
	// Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
	// con l'opzione /str oppure ricompilare il progetto VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iKiwi.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
		///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap Download_50 {
			get {
				object obj = ResourceManager.GetObject("Download 50", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Error {
			get {
				object obj = ResourceManager.GetObject("Error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap FacebookLogo {
			get {
				object obj = ResourceManager.GetObject("FacebookLogo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Hub {
			get {
				object obj = ResourceManager.GetObject("Hub", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Icon ikiwi {
			get {
				object obj = ResourceManager.GetObject("ikiwi", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap iKiwi_splash {
			get {
				object obj = ResourceManager.GetObject("iKiwi splash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Internet {
			get {
				object obj = ResourceManager.GetObject("Internet", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Love {
			get {
				object obj = ResourceManager.GetObject("Love", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Peers_50 {
			get {
				object obj = ResourceManager.GetObject("Peers 50", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Search_50 {
			get {
				object obj = ResourceManager.GetObject("Search 50", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Shared_directory {
			get {
				object obj = ResourceManager.GetObject("Shared directory", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Shared_files_50 {
			get {
				object obj = ResourceManager.GetObject("Shared files 50", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Status_OK {
			get {
				object obj = ResourceManager.GetObject("Status_OK", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Status_Problem {
			get {
				object obj = ResourceManager.GetObject("Status_Problem", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Tools_50 {
			get {
				object obj = ResourceManager.GetObject("Tools 50", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
